services:
  - type: web
    name: novacool_rag
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app_flask:app
    pythonVersion: 3.12.3
    autoDeploy: true
    envVars:
      - key: OPENAI_API_KEY
        sync: false
