services:
  - type: web
    name: novacool_rag-app
    env: python
    plan: starter
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: gunicorn app_flask:app
    autoDeploy: true
    envVars:
      - key: OPENAI_API_KEY
        sync: false
    disk:
      name: data
      mountPath: /opt/render/project/src/data
      sizeGB: 2
